#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
    /config/media \
    /run/obico

if [ ! -f "/.setup" ]; then
    echo "Initialising Obico"
    cd /app/obico/backend

    python3.10 manage.py migrate
    python3.10 manage.py collectstatic -v 2 --noinput

    touch "/.setup"
fi

# permissions
chown -R abc:abc \
    /config \
    /app \
    /run/obico
