#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
    /config/media \
    /run/obico

echo "Initialising Obico"
source /lsiopy/3.10/backend/bin/activate
cd /app/obico/backend

python3.10 manage.py migrate
python3.10 manage.py collectstatic -v 2 --noinput

# permissions
chown -R abc:abc \
    /config \
    /app \
    /run/obico
